DEFAULT_VIDEO_FPS = 30.0
SALIENCY_FALLBACK_FPS = 25.0

EMBEDDINGS_ROOT = "embeddings"

CLIP_MODEL_ID = "openai/clip-vit-large-patch14"
DEPTH_MODEL_ID = "depth-anything/Depth-Anything-V2-Large-hf"
DINO_MODEL_ID = "facebook/dino-vitb8"
DINO_INPUT_SIZE = 224
DINO_PATCH_SIZE = 8
YOLO_OBJECT_MODEL_ID = "yolov8n.pt"

AESTHETIC_HEAD_URL = "https://github.com/christophschuhmann/improved-aesthetic-predictor/raw/main/sac+logos+ava1-l14-linearMSE.pth"
AESTHETIC_HEAD_FILENAME = "aesthetic_linear_v2.pth"

EDIT_PACE_WINDOW_SEC = 60
EDIT_PACE_MIN_WINDOW_SEC = 15
EMBEDDING_DRIFT_SMOOTH_WINDOW_SEC = 3
OCR_CONFIDENCE_THRESHOLD = 0.5

BUMPER_WINDOW_SEC = 20
BUMPER_STEP_SEC = 2
BUMPER_MIN_TRIM_SEC = 2
BUMPER_HIST_BINS = (16, 16)
BUMPER_CROSS_THRESH = 0.85
BUMPER_MAX_SEC = 30
BUMPER_SINGLE_BOUNDARY_PERCENTILE = 97
BUMPER_SINGLE_MIN_SEC = 3
BUMPER_SINGLE_MAX_SEC = 20
BUMPER_SINGLE_TOP_K = 3

SHORT_INSERT_THRESHOLD_SEC = 2.0
SHORT_INSERT_RATE_WINDOW_SEC = 30
SPEAKER_SAMPLE_EVERY = 25
OVERLAY_PROB_THRESHOLD = 0.7
VISUAL_COMPLEXITY_ENTROPY_WEIGHT = 0.6
VISUAL_COMPLEXITY_SHARPNESS_WEIGHT = 0.4
SCENE_NOVELTY_HIST_BINS = (32, 32)

VIDEO_INTELLIGENCE_RHYTHM_WINDOW_SEC = 30
VIDEO_INTELLIGENCE_RHYTHM_LAGS = 5
VIDEO_INTELLIGENCE_SYNC_WINDOW_SEC = 10
VIDEO_INTELLIGENCE_INTRO_SEC = 30
VIDEO_INTELLIGENCE_SURPRISE_WINDOW_SEC = 30
VIDEO_INTELLIGENCE_MIN_PERIODS_ROLL = 3
VIDEO_INTELLIGENCE_TARGET_SR = 22050
VIDEO_INTELLIGENCE_FRAME_LEN = 2048
VIDEO_INTELLIGENCE_HOP_LEN = 512
